### ISSUE TITLE
GetSysmonTree.ps1 gives error and stuck

### ISSUE THREAD

**Issue by nimaforoughi** [gtworek/PSBits#15]
![image](https://user-images.githubusercontent.com/90676852/176989414-f972ef55-48cf-4233-87e9-2bef4fa834ac.png)
Hello This is the error I get, and it will never go through...

**Comment by nimaforoughi** [comment]
![image](https://user-images.githubusercontent.com/90676852/176989734-1f67aeff-9233-4389-8fda-6d7b08b9094d.png)

**Comment by k4nfr3** [comment]
Hi, this script looks awesome.
i also have the same error. 
@0gtweet : Is there a minimum version of Sysmon required ?
regards

**Comment by k4nfr3** [comment]
Running version 13.33
![image](https://user-images.githubusercontent.com/45294916/177004776-5f5ac3ee-0f1c-4ba4-aea6-94bde160be9d.png)

**Comment by k4nfr3** [comment]
Seems to be related to some Events which craches it

![image](https://user-images.githubusercontent.com/45294916/177005337-b0cf687f-3910-4a53-aae6-7b6b9fcfc6ac.png)

**Comment by nimaforoughi** [comment]
Regardless of the many errors it finally works, but it takes a lot of time.

**Comment by gtworek** [comment]
I have no idea what's wrong, but my script does even not obtain data for analysis. For some reason Get-WinEvent fails reading the log. I will try to investigate it, but it's not an issue about the script itself.
