### ISSUE TITLE
Powershell issue, Can you help?

### ISSUE THREAD

**Issue by jberman280** [gtworek/PSBits#2]
After i run Openvpn Ps1 i get this issue:

**Comment by jberman280** [comment]
Exception calling "Unprotect" with "3" argument(s): "Key not valid for use in specified state.
"
At C:\users\merri\downloads\OpenVPNDecrypt.ps1:13 char:5
+     $decryptedbytes = [System.Security.Cryptography.ProtectedData]::U ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicException

Exception calling "GetString" with "1" argument(s): "Array cannot be null.
Parameter name: bytes"
At C:\users\merri\downloads\OpenVPNDecrypt.ps1:18 char:5
+     Write-Host ($item.PSChildName), ([System.Text.Encoding]::Unicode. ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Exception calling "Unprotect" with "3" argument(s): "Key not valid for use in specified state.
"
At C:\users\merri\downloads\OpenVPNDecrypt.ps1:13 char:5
+     $decryptedbytes = [System.Security.Cryptography.ProtectedData]::U ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicException

Exception calling "GetString" with "1" argument(s): "Array cannot be null.
Parameter name: bytes"
At C:\users\merri\downloads\OpenVPNDecrypt.ps1:18 char:5
+     Write-Host ($item.PSChildName), ([System.Text.Encoding]::Unicode. ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], M

**Comment by gtworek** [comment]
You can start your script with "Add-Type -AssemblyName System.Security" and "Add-Type -AssemblyName System.Text.Encoding"
It should help.
