### ISSUE TITLE
Hidden Shadow can't be unhidden.

### ISSUE THREAD

**Issue by migmam** [gtworek/PSBits#21]
Hi! I'm currently having an issue with this scenario:
I have just one Shadowcopy (number 1). I hide this Shadowcopy.
I create a new one Shadowcopy (number 2). 
Since I want to have the most recent one hidden. I try to unhide the number 1 and hide the number 2.
The result is:
Number 1 is not unhide. An error message is shown.
Number 2 is hidden.
I can't recover anymore the number 1.

**Comment by gtworek** [comment]
Sincerely no idea. Maybe the hidden one does not exist anymore?

**Comment by migmam** [comment]
Hi.
Tested again and the if I try to unhide a shadow this is the error message:
ERROR: CreateFile() returned 2
So the shadow is not accessible or deleted.

**Comment by gtworek** [comment]
Thank you for the update. If the shadow doesn't exist anymore (automatically or manually deleted) it makes sense it cannot be unhidden. :)

**Comment by migmam** [comment]
Hi! That's the problem. It was not deleted automatically or manually. It seems that once it is hidden it can't be recovered anymore.

**Comment by migmam** [comment]
![error_shadow](https://user-images.githubusercontent.com/14196643/224540966-6e66d495-b563-4900-84e6-b60341e7ef77.png)

**Comment by migmam** [comment]
![error_shadow](https://user-images.githubusercontent.com/14196643/224543274-5da4eae6-a819-434a-b493-e15d3c069638.png)
