### ISSUE TITLE
Error running NPPSPy.c

### ISSUE THREAD

**Issue by couchpotato78** [gtworek/PSBits#3]
Hi,

I get the following message when I run NPPSPy.c

C:\Win-builds\bin>gcc c:\temp\NPPSPy.c
C:\temp\NPPSPy.c: In function 'SavePassword':
C\temp\NPPSPy.c:53:3: warning: passing argument 1 of 'CreateFileA' from incompatible pointer type [enabled by default]
   NULL);
   ^
In file included from c:\win-builds\i686-w64-mingw32\include\winbase.h:18:0,
                 from c:\win-builds\i686-w64-mingw32\include\windows.h:70,
                 from c:\temp\NPPSPy.c:1:
C:\win-builds\i686-w64-mingw32\include\fileapi.h:45:28: note: expected 'LPCSTR' but argument is of type 'short unsigned int *'
   WINBASEAPI HANDLE WINAPI CreateFileA (LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
                            ^
C:/win-builds/bin/../lib/gcc/i686-w64-mingw32/4.8.3/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x39): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status

**Comment by gtworek** [comment]
It should be working right now. Wrongly assumed whole world runs Unicode.
