### ISSUE TITLE
Get-UnusualRootCerts outputs 245C97DF7514E7CF2DF8BE72AE957B9E04741E85      

### ISSUE THREAD

**Issue by ckrueger1979** [gtworek/PSBits#30]
Hi,

the script outputs:
LocalMachine\Root\245C97DF7514E7CF2DF8BE72AE957B9E04741E85      
OU=Copyright (c) 1997 Microsoft Corp., OU=Microsoft Time Stamping Service Root, OU=Microsoft Corporation, O=Microsoft Trust Network

Which seem to be legit (there are many google hits, where people post there cert store content)

Any idea why it's missing it microsofts official list?

greetings
Carsten

**Comment by gtworek** [comment]
Absolutely no idea. I will add an option to "whitelist" own certs from text file soon. It will not solve the issue but may make the script more practical.
