### ISSUE TITLE
StopAndDisableDefaultSpoolers.ps1 - another default printers 

### ISSUE THREAD

**Issue by mikas-khb** [gtworek/PSBits#8]
Hi
i have few another default printers:
```
Printer found: Send to Microsoft OneNote 16 Driver
Printer found: Microsoft Shared Fax Driver
```
may be add this to script?

**Comment by gtworek** [comment]
Sure. Can you specify which OS is it? I guess OneNote is about Office.

**Comment by mikas-khb** [comment]
OS - Windows 10. 
Yes? OneNote is MS Office component.

**Comment by gtworek** [comment]
Done. Thank you!
